"""Initial migration

Revision ID: f2040fdbcc2d
Revises: 
Create Date: 2025-01-04 08:47:05.892204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2040fdbcc2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Add a name for the foreign key constraint
        batch_op.create_foreign_key('fk_sharedpassword_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('is_used')
        batch_op.drop_column('token')
        batch_op.drop_column('expiry_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('is_used', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
