"""add totp_secret column

Revision ID: c5791440926e
Revises: 71555b222fd7
Create Date: 2025-01-07 12:10:11.266767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5791440926e'
down_revision = '71555b222fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('site_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('shared_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('shared_password', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.alter_column('site_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('strength')

    op.drop_table('password_history')
    # ### end Alembic commands ###
